'use strict';

const { assert, expect } = require( 'chai' );

const {
	define,
	lookup,
	SymbolConstructorName,
	MNEMONICA,
	utils: {
		parse,
		parent
	},
	errors,
} = require( '..' );

const tests = ( opts ) => {

	const {
		user,
		userPL1,
		userPL2,
		userTC,
		evenMore,
		EmptyType,
	} = opts;

	describe( 'parse tests', () => {

		const samples = require( './parseSamples' );
		
		it( 'expect wrong parse invocation throw for undefined and constructor-less', () => {
			expect( () => parse( undefined ) ).to.throw( errors.WRONG_MODIFICATION_PATTERN );
			expect( () => parse( Object.create( null ) ) ).to.throw( errors.WRONG_MODIFICATION_PATTERN );
		} );

		it( 'expect parse(null) to return the empty shape', () => {
			// null is the one non-object input parse accepts:
			// "nothing was given" — every field empty, parent undefined
			const nullParsed = parse( null );
			assert.deepEqual( nullParsed, {
				name   : undefined,
				props  : {},
				self   : null,
				proto  : undefined,
				joint  : {},
				parent : undefined
			} );
			assert.strictEqual( nullParsed.parent, undefined );
			assert.isNull( nullParsed.self );
		} );

		try {
			parse( Object.getPrototypeOf( user ) );
		} catch ( error ) {
			it( 'expect wrong parse invocation throw', () => {
				expect( error ).to.be.an
					.instanceof( errors
						.WRONG_ARGUMENTS_USED );
				expect( error ).to.be.an
					.instanceof( Error );
			} );
		}
		try {
			parse( Object.getPrototypeOf( Object.getPrototypeOf( userPL1 ) ) );
		} catch ( error ) {
			it( 'expect wrong parse invocation throw', () => {
				expect( error ).to.be.an
					.instanceof( errors
						.WRONG_ARGUMENTS_USED );
				expect( error ).to.be.an
					.instanceof( Error );
			} );
		}

		debugger;
		const parsedUser = parse( user );
		const parsedUserTC = parse( userTC );
		const results = {
			parsedUser,
			parsedUserPL1 : parse( userPL1 ),
			parsedUserPL2 : parse( userPL2 ),

			parsedUserTC,
			parsedEvenMore : parse( evenMore ),
		};

		// PARSE_SAMPLES_REGEN=1: rewrite test/parseSamples.js from the real
		// parse output. The samples encode the expected parent INSTANCE
		// chains — regenerate them whenever parse().parent semantics change,
		// and review the diff (it is the expectation, not a mere snapshot).
		if ( process.env.PARSE_SAMPLES_REGEN ) {
			const { inspect } = require( 'util' );
			const shape = ( parsed ) => {
				if ( parsed === undefined || parsed === null ) {
					return undefined;
				}
				const node = {
					name  : parsed.name,
					props : parsed.props,
					joint : parsed.joint,
					self  : { ...parsed.props },
					proto : { ...parsed.joint },
				};
				// parsed.parent is the RAW parent instance (undefined at the
				// root) — parse it back before shaping the subtree
				if ( parsed.parent === undefined || parsed.parent === null ) {
					node.parent = null;
					return node;
				}
				node.parent = shape( parse( parsed.parent ) );
				return node;
			};
			const shaped = {};
			Object.keys( results ).forEach( ( key ) => {
				shaped[ key ] = shape( results[ key ] );
			} );
			const body = inspect( shaped, {
				depth       : null,
				compact     : false,
				breakLength : 60,
			} );
			require( 'fs' ).writeFileSync(
				'./test/parseSamples.js',
				`'use strict';\n\n// Regenerated by test/parse.js with PARSE_SAMPLES_REGEN=1 —\n// expected parse() trees for the CURRENT parse().parent semantics.\n// Review the diff when regenerating: this file is the expectation.\n\nmodule.exports = ${ body };\n`
			);
			return;
		}

		it( 'expect parent to be the parent instance', () => {
			// root instances have no parent — and NO PARENT IS null
			assert.equal( parsedUser.parent, null );
			assert.equal( parsedUserTC.parent, null );
			// the same object utils.parent() returns, not a prototype layer
			assert.equal( results.parsedUserPL1.parent, parent( userPL1 ) );
			assert.equal( results.parsedUserPL2.parent, parent( userPL2 ) );
			assert.equal( results.parsedEvenMore.parent, parent( evenMore ) );
		} );

		it( 'expect parse of parent to work and name the parent type', () => {
			const reparsed = parse( results.parsedUserPL1.parent );
			assert.equal( reparsed.name, 'UserType' );
			// and the parent of the parent instance parses to null (root)
			assert.strictEqual( reparsed.parent, null );
		} );

		it( 'expect strictChain unchained construction to name the expected parent', () => {
			// the null-prev + sentinel path of the strictChain check: a
			// synthesized root instance has NO parent (null), the raw
			// __parent__ is the internal sentinel — the message NAMES the
			// expected parent instead of falling back to "some instance"
			const PinRoot = define( 'StrictChainPinRoot', function () {} );
			PinRoot.define( 'StrictChainPinSub', function () {} );
			const PinSub = lookup( 'StrictChainPinRoot.StrictChainPinSub' );
			let strictChainError;
			try {
				new PinSub();
			} catch ( error ) {
				strictChainError = error;
			}
			expect( strictChainError ).to.be.an.instanceof( errors.WRONG_MODIFICATION_PATTERN );
			expect( strictChainError.message ).to.equal(
				'wrong modification pattern : should inherit from StrictChainPinRoot but made on StrictChainPinSub'
			);
		} );

		it( 'expect utils.parent null/undefined semantics', () => {
			// NO PARENT IS null (a root — the end of the chain)
			assert.strictEqual( parent( user ), null );
			assert.strictEqual( parent( userTC ), null );
			// props-less objects have no construction record: null as well
			assert.strictEqual( parent( {} ), null );
			// the path form SEARCHES: not-found stays undefined, and a
			// root has no chain to search
			assert.strictEqual( parent( user, 'UserType' ), undefined );
			assert.strictEqual( parent( userPL1, 'UserTypePL1' ), undefined );
			// found paths still return the parent instance
			assert.equal( parent( userPL1, 'UserType' ), user );
		} );

		it( 'expect props-less objects to parse with no parent', () => {
			// a plain object has no construction props record at all
			const parsedPlain = parse( {} );
			assert.equal( parsedPlain.name, 'Object' );
			assert.strictEqual( parsedPlain.parent, null );
		} );

		it( 'expect proper first instance in chain constructor', () => {
			assert.equal( parsedUser.self[ SymbolConstructorName ], MNEMONICA );
			assert.equal( parsedUserTC.self[ SymbolConstructorName ], MNEMONICA );
		} );

		it( 'should be ok with broken constructor chain', () => {

			const oneElseEmpty = new EmptyType();
			const oneElseEmptyProto = Object.getPrototypeOf( Object.getPrototypeOf( Object.getPrototypeOf( oneElseEmpty ) ) );

			// oxlint-disable-next-line no-unused-expressions
			expect( () => {
				oneElseEmptyProto[ SymbolConstructorName ] = undefined;
			} ).to.throw;
			// oxlint-disable-next-line no-unused-expressions
			expect( () => {
				delete oneElseEmptyProto[ SymbolConstructorName ];
			} ).to.throw;
		} );

		let count = 0;
		const compare = ( result, sample ) => {
			Object.entries( result ).forEach( entry => {
				const [ name, value ] = entry;
				
				const sampleValue = sample[ name ];

				// if (sampleValue === undefined) {
				// 	key_name;
				// 	result;
				// 	sample;
				// 	entry;
				// 	name;
				// 	value;
				// 	debugger;
				// }

				if ( name === 'parent' ) {
					// parent is the parent INSTANCE now: parse it back
					// before comparing against the sample's parsed tree;
					// a root instance parses to undefined
					if ( value === undefined || value === null ) {
						it( `parse results should have same "parent" with samples for ${name}`, () => {
							count++;
							assert.deepEqual( value, sampleValue );
						} );
						return;
					}
					const parsedValue = parse( value );
					const cmpResult = compare( parsedValue, sampleValue );
					return cmpResult;
				}

				if ( name === 'self' ) {
					it( `parse results should have same "self" with samples for ${name}`, () => {
						count++;
						assert.deepOwnInclude( value, sampleValue );
						assert.deepOwnInclude( sampleValue, value );
					} );
					return;
				}
				if ( name === 'proto' ) {
					it( `parse results should have same "proto" with samples for ${name}`, () => {
						count++;
						// assert.deepInclude(value, sampleValue);
						assert.deepInclude( sampleValue, value );
					} );
					return;
				}

				if ( name === 'constructor' ) return;
				
				it( `parse results should have same props with samples for "${name}"`, () => {
					count++;
					assert.deepEqual( value, sampleValue );
				} );
			} );
		};

		Object.keys( results ).forEach( key => {
			compare( results[ key ], samples[ key ] );
			// TODO: it was reversed, though now it is not working
			// compare( samples[ key ], results[ key ] );
		} );

		// 65 = 5 checks per parsed level (name/props/joint/self/proto) × 12
		// levels + 1 undefined-parent leaf check × 5 roots. It was 25
		// because parent used to be a prototype layer with no enumerable
		// own props — the recursive samples compared vacuously. Now parent
		// is the parent INSTANCE, every level of the samples is actually
		// verified, so the honest count is higher.
		const checksCount = 65;

		it( `should have exactly ${checksCount} amount of generated results~sample parse tests`, () => {
			assert.equal( count, checksCount );
		} );

	} );

};

module.exports = tests;
