/* eslint-disable space-before-function-paren */
'use strict';

import type {
	CreateTypesCollectionFunction,
	IDEF,
	hook,
	hooksTypes,
	constructorOptions,
	Proto,
	IDefinitorInstance,
	Constructor,
	DecoratedClass,
	TypeClass,
	TypeAbsorber,
	MnemonicaModule,
	TypeConstructor,
	InstanceResult,
	Merge
} from './types';

import TypesUtils from './api/utils/index';
export const {
	isClass,
	findSubTypeFromParent,
} = TypesUtils;

export type {
	IDEF, TypeConstructor, _Internal_TC_, Proto, ProtoFlat,
	hooksOpts, hook, hooksTypes, TypesCollection
} from './types';
export {
	getProps, setProps 
} from './api/types/Props';

import { constants } from './constants';
const { odp } = constants;

import * as errorsApi from './api/errors';
import { descriptors } from './descriptors';

const { WRONG_MODIFICATION_PATTERN } = descriptors.ErrorsTypes;

import mnemosynes from './api/types/Mnemosyne';
const { prepareSubtypeForConstruction } = mnemosynes;

export const { defaultTypes, } = descriptors;

function checkThis(pointer: typeof mnemonica | typeof exports | unknown): boolean {
	const result = pointer === mnemonica || pointer === exports;
	return result;
}


// Define function using TypeAbsorber interface with proper type casting
export const define = function <
	T extends object,
	P extends object = object,
	N extends Proto<P, T> = Proto<P, T>,

	// here IDefinitorInstance is a CONSTRUCTOR !!!
	R extends IDefinitorInstance<N> = IDefinitorInstance<N>
>(
	this: unknown,
	TypeName?: string | CallableFunction | NewableFunction,
	// Allow both strict IDEF and more flexible function signatures
	constructHandler?: IDEF<T> | CallableFunction | NewableFunction | object | boolean,
	config?: constructorOptions,
): R {
	const types = checkThis(this) ? defaultTypes : this || defaultTypes;
	// Type assertion needed because TypesCollectionProxy is a Proxy
	const defineResult = (types as { define: TypeAbsorber })
		.define(
			TypeName as string,
			constructHandler as IDEF<T>,
			config
		) as unknown as R;
	return defineResult;
} as TypeAbsorber;

export const lookup = function (
	this: unknown,
	TypeNestedPath: string
): TypeClass | undefined {
	const types = checkThis(this) ? defaultTypes : this || defaultTypes;
	// Type assertion needed because TypesCollectionProxy is a Proxy
	const lookupResult = (types as { lookup: (path: string) => TypeClass | undefined }).lookup(TypeNestedPath);
	return lookupResult;
};

/**
 * Default TypeRegistry interface - augment this in your project via
 * TypeScript declaration merging. The augmentation can be hand-written
 * in a .d.ts file (small projects) or generated by @mnemonica/tactica.
 *
 * Uses `TypeConstructor<never>` as the index value type to enforce
 * augmentation: without it, any key lookup resolves to a useless type
 * because `TypeConstructor<never>` is not assignable to concrete types.
 *
 * Example (in a hand-written .d.ts, or generated by tactica in
 * .tactica/registry.ts):
 *   declare module 'mnemonica' {
 *     interface TypeRegistry {
 *       'MyType': new (...args: unknown[]) => MyTypeInstance;
 *     }
 *   }
 *
 * See docs/typed-lookup.md for both paths side by side.
 */
export interface TypeRegistry {
	[key: string]: TypeConstructor<never>;
}

/**
 * Type-safe lookup function. Requires a TypeRegistry augmentation —
 * hand-written in a .d.ts (small projects) or generated by
 * @mnemonica/tactica (auto-synced from your define() calls).
 *
 * At runtime this delegates to lookup(). The type safety is
 * compile-time only: TypeScript resolves the key against the augmented
 * TypeRegistry and returns the constructor's type signature.
 *
 * Usage (once TypeRegistry is augmented):
 *   const SomeType = lookupTyped('SomeType');
 *   const instance = new SomeType({ ... }); // Full type safety!
 *
 * See docs/typed-lookup.md for both augmentation paths side by side.
 */
export const lookupTyped = function <
	const K extends keyof TypeRegistry
>(
	this: unknown,
	TypeNestedPath: K
): TypeRegistry[K]  {
	const types = checkThis(this) ? defaultTypes : this || defaultTypes;
	const lookupResult = (types as { lookup: (path: string) => unknown })
		.lookup(TypeNestedPath as string) as TypeRegistry[K];
	return lookupResult;
};


const $run = function <E extends object, T extends object, S extends Proto<E, T>>(
	entity: E,
	Ctor: IDEF<T>,
	args: unknown[]
): {
		[key in keyof S]: S[key]
	} {

	// debugger;
	// @ts-expect-error - extracting TypeName from function
	const { TypeName } = Ctor;
	const Cstr = prepareSubtypeForConstruction(
		TypeName,
		entity
	) as unknown as { new(...ars: unknown[]): unknown };
	// TODO: check lines below and if Constructor is not mnemonized ...
	if (Cstr === undefined) {
		const ErrorCtor = WRONG_MODIFICATION_PATTERN as unknown as new (msg: string) => Error;
		throw new ErrorCtor(`[ ${TypeName} ] is not defined as a Type Constructor on used instance`);
	}
	const runResult = new Cstr(...args);
	// @ts-expect-error - returning result as merged proto type
	return runResult;
};

// TODO: apply instance .to type .with arguments
export const apply = function <E extends object, T extends object, S extends Proto<E, T>>(
	entity: E,
	Ctor: IDEF<T>,
	args: unknown[] = []
): InstanceResult<Merge<E, T>, constructorOptions> {
	const runResult = $run<E, T, S>(
		entity,
		Ctor,
		args
	);
	const result = runResult as unknown as InstanceResult<Merge<E, T>, constructorOptions>;
	return result;
};

// TODO: call type .by instance .with arguments
export const call = function <E extends object, T extends object, S extends Proto<E, T>>(
	entity: E,
	Ctor: IDEF<T>,
	...args: unknown[]
): InstanceResult<Merge<E, T>, constructorOptions> {
	const runResult = $run<E, T, S>(
		entity,
		Ctor,
		args
	);
	const result = runResult as unknown as InstanceResult<Merge<E, T>, constructorOptions>;
	return result;
};

// TODO: bind type .with instance → (...args)
export const bind = function <E extends object, T extends object, S extends Proto<E, T>>(
	entity: E,
	Ctor: IDEF<T>
): (...args: unknown[]) => InstanceResult<Merge<E, T>, constructorOptions> {
	const result = (...args: unknown[]) => {
		const runResult = $run<E, T, S>(
			entity,
			Ctor,
			args
		);
		const typedResult = runResult as unknown as InstanceResult<Merge<E, T>, constructorOptions>;
		return typedResult;
	};
	return result;
};

export const decorate = function <
	T extends Constructor<object> | constructorOptions | undefined = undefined
>(
	target?: T,
	config?: constructorOptions
): <U extends Constructor<object>>(cstr: U) => DecoratedClass<U> {
	const opts = (config === undefined && typeof target === 'object' && !(target instanceof Function))
		? target as constructorOptions
		: config;

	const parentType = (target instanceof Function)
		? target as Constructor<object>
		: undefined;

	const decorator = function <U extends Constructor<object>>(cstr: U): DecoratedClass<U> {
		const { name } = cstr;
		if (parentType === undefined) {
			const decoratorResult = define(
				name,
				cstr as IDEF<object>,
				opts
			) as unknown as DecoratedClass<U>;
			return decoratorResult;
		}
		const parent = parentType as unknown as {
			define: TypeAbsorber;
		};
		const defineResult = parent.define(
			name,
			cstr as IDEF<object>,
			opts
		) as unknown as DecoratedClass<U>;
		return defineResult;
	};
	return decorator;
};


export const registerHook = function <T extends Constructor<T>>(
	Ctor: DecoratedClass<T>,
	hookType: hooksTypes,
	cb: hook
): void {
	Ctor.registerHook(
		hookType,
		cb
	);
};

export const mnemonica = Object.entries({

	define,
	lookup,
	apply,
	call,
	bind,
	decorate,
	registerHook,

	...descriptors,

	...errorsApi,
	...constants,

}).reduce(
	(acc: { [index: string]: unknown }, entry: [string, unknown]) => {
		const [ name, code ] = entry;
		odp(
			acc,
			name,
			{
				get() {
					return code;
				},
				enumerable : true
			}
		);
		return acc;
	},
	{}
) as MnemonicaModule;

import * as api from './api';

export const {
	define: _define,
	lookup: _lookup
} = api.types;

export const {

	SymbolParentType,
	SymbolConstructorName,
	SymbolDefaultTypesCollection,
	SymbolConfig,
	MNEMONICA,
	MNEMOSYNE,
	TYPE_TITLE_PREFIX,
	ErrorMessages,

} = mnemonica;

// Export createTypesCollection with proper type
export const createTypesCollection: CreateTypesCollectionFunction =
	mnemonica.createTypesCollection as CreateTypesCollectionFunction;


export const defaultCollection = (defaultTypes as { subtypes: Map<string, object> }).subtypes;
export const errors = descriptors.ErrorsTypes;

export { utils } from './utils';
export { defineStackCleaner } from './utils';
/* eslint-enable space-before-function-paren */
